### ISSUE TITLE
Init fails to produce a valid copy of composer.json

### ISSUE THREAD

**Issue by thealexwheeler** [ideasonpurpose/docker-wordpress-dev#68]
@joemaller I've been playing around with this project and I have run into a little trouble with it.  Seeing as I have already gone down the rabbit hole I thought I would create a GH issue to document this issue and offer a potential solution.

From my testing, since v1.0.3 (specifically commit 9a40ef6), the code in **bin/wp-init.sh** that produces the composer.json file renders an empty file.  The result of this is that when running `npm run bootstrap`  an error is returned for the composer:install step: _"install: missing file operand"_.

It appears that the following command in **bin/wp-init.sh** is the culprit:

`jq -s '.[0] * .[1] |
       .config."vendor-dir" = "wp-content/themes/'"${NAME}"'/vendor" |
       .autoload."psr-4"."IdeasOnPurpose\\" = ["wp-content/themes/'"${NAME}"'/lib"] |
       .name //= "ideasonpurpose/'"${NAME}"'" |
       .description = "'"${DESCRIPTION}"'" |
       .repositories |= sort_by(.url) |
       .require = (.require | to_entries | sort_by(.key) | from_entries) |
       {name, description, version, authors, config, autoload} * . |
       with_entries(select(.value))' \
  /usr/src/boilerplate-composer.json /tmp/composer.json | cat >/usr/src/site/composer.json`

Specifically: ` .repositories |= sort_by(.url)`

In 9a40ef6 the following code was removed from **src/boilerplate-composer.json**:

` "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/ideasonpurpose/wp-vimeo-embed",
      "no-api": true
    }
  ]`

As a result when the jq command attempts to sort the repositories object by url it cannot find those keys and the jq command returns the following error:  jq: error (at /tmp/composer.json:31): _"Cannot iterate over null (null)"_

![image](https://github.com/ideasonpurpose/docker-wordpress-dev/assets/13472185/a235318c-851a-4575-bdc5-e9088c79fd0d)

This issue occurs whenever the default composer.json and an existing project composer.json both omit the repositories object with a url key.  For existing projects which started before v1.0.3 this issue will not occur as the existing composer.json file will provide the object to merge with the default file.

Removing the  ` .repositories |= sort_by(.url)` statement fixed this issue for me.

**Comment by joemaller** [comment]
@thealexwheeler Thanks for taking the time to look into this!

**Comment by joemaller** [comment]
See also #64
